name: Publish VSCode Extension

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check commit message
        id: check_msg
        run: echo "::set-output name=trigger::$(git log -1 --pretty="%B" | grep -i 'bump')"
      
      - name: Stop job if 'bump' not found in commit message
        if: steps.check_msg.outputs.trigger == ''
        run: echo "'bump' not found in commit message, stopping job" && exit 0
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Install Dependencies
        run: npm install

      - name: Publish Extension
        run: vsce publish minor
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: vscode-extension
          path: '*.vsix'
